site_name: Spigot 中文开发指南
repo_url: https://github.com/lingluo-hub/SpigotMC
edit_uri: edit/main/docs/
repo_name: lingluo-hub/SpigotMC
copyright: Copyright &copy; 2012 - 2022 SpigotMC Pty. Ltd. && Ling Luo

nav:
  - 首页:
    - index.md
  - 官方使用文档:
    - official-spigot-using/index.md
    - 构建工具: official-spigot-using/buildtools.md
    - Spigot 安装: official-spigot-using/spigot-installation.md
    - Spigot 配置: official-spigot-using/spigot-configuration.md
    - 服务器图标: official-spigot-using/server-icon.md
    - Spigot 启动参数: official-spigot-using/start-up-parameters.md
    - Spigot 命令与权限: official-spigot-using/spigot-commands.md
    - 提示、技巧和教程:
      - official-spigot-using/tips-tricks-tutorials/index.md
      - 禁用 Netty: official-spigot-using/tips-tricks-tutorials/disabling-netty.md
      - 排查服务器崩溃: official-spigot-using/tips-tricks-tutorials/isolating-crashes.md
      - 阻止世界下载者: official-spigot-using/tips-tricks-tutorials/discouraging-users-from-using-map-downloaders.md
  - 官方开发文档:
    - official-plugin-development/index.md
    - 用 Gradle Groovy 构建你的 Spigot 插件: official-plugin-development/spigot-gradle.md
    - 代码简洁之道: official-plugin-development/clean-code.md
    - 命令别名: official-plugin-development/command-alias.md
    - Plugin.yml: official-plugin-development/plugin.yml.md
    - 创建一个简单的命令: official-plugin-development/create-a-simple-command.md
    - 使用事件 API: official-plugin-development/using-the-event-api.md
    - 使用配置 API: official-plugin-development/creating-a-config-file.md
    - 使用 MongoDB 数据库: official-plugin-development/using-mongodb.md
    - 结合 Morphia 使用 MongoDB: official-plugin-development/mongodb-with-morphia.md
    - 配置 MySQL 数据库与插件集成: official-plugin-development/mysql-database-integration-with-your-plugin.md
    - 创建更新检查器: official-plugin-development/creating-an-update-checker-that-checks-for-updates.md
    - 创建外部库: official-plugin-development/creating-external-libraries.md
    - 为 Spigot 创建离线 Javadoc: official-plugin-development/creating-offline-javadoc-for-the-spigot-api.md
    - 向玩家发送标题 - Packets: official-plugin-development/send-title-to-player-packets.md
    - 设置 WorldEdit API: official-plugin-development/setting-up-the-worldedit-api.md
  - 插件代码参考:
    - plugin-snippets/index.md
    - 异步处理数据库: plugin-snippets/asynchronously-working-with-a-database.md
    - 自动销售物品: plugin-snippets/auto-selling-items.md
    - 使用配置文件: plugin-snippets/config-files.md

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  language: zh
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Red Hat Text
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - glightbox
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lingluo-hub
      name: Ling Luo on GitHub
