site_name: Spigot 中文开发指南
repo_url: https://github.com/lingluo-hub/SpigotMC
edit_uri: edit/main/docs/
repo_name: lingluo-hub/SpigotMC
copyright: Copyright &copy; 2012 - 2022 SpigotMC Pty. Ltd. && Ling Luo

nav:
  - 什么是 Spigot:
    - index.md
  - 官方使用文档:
    - official-spigot-using/index.md
    - Spigot 安装: official-spigot-using/spigot-installation.md
    - Spigot 配置: official-spigot-using/spigot-configuration.md
  - 官方开发文档:
    - official-plugin-development/index.md
    - 用 Gradle Groovy 构建你的 Spigot 插件: official-plugin-development/spigot-gradle.md
    - 代码简洁之道: official-plugin-development/clean-code.md
    - 命令别名: official-plugin-development/command-alias.md
    - Plugin.yml: official-plugin-development/plugin.yml.md
    - 创建一个简单的命令: official-plugin-development/create-a-simple-command.md
    - 使用事件 API: official-plugin-development/using-the-event-api.md
    - 使用配置 API: official-plugin-development/creating-a-config-file.md
    - 使用 MongoDB 数据库: official-plugin-development/using-mongodb.md
    - 创建更新检查器: official-plugin-development/creating-an-update-checker-that-checks-for-updates.md
    - 创建外部库: official-plugin-development/creating-external-libraries.md
    - 为 Spigot 创建离线 Javadoc: official-plugin-development/creating-offline-javadoc-for-the-spigot-api.md
  - 插件代码参考:
    - plugin-snippets/index.md

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  language: zh
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    # text: Ubuntu
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lingluo-hub
      name: Ling Luo on GitHub
